### ISSUE TITLE
PhoneNumber class shouldn't be internal

### ISSUE THREAD

**Issue by matir91** [Tap-Payments/goSellSDK-Android#11]
When you are creating a customer (using `CustomerBuilder`), you can set the phone number using the `PhoneNumber` class.
The `PhoneNumber` package class is `company.tap.gosellapi.internal.api.models` instead of `company.tap.gosellapi.open.models` and I think it's wrong because it's not an internal class.

**Comment by HaithamSheshtawy** [comment]
You are right. But even internal `PhoneNumber` class  is not restricted to SDK, hence you can use it with no issues.
