### ISSUE TITLE
[2.2] Security issue, log system.

### ISSUE THREAD

**Issue by matir91** [Tap-Payments/goSellSDK-Android#12]
Sometime the app log important information in the logger system, for example:

```
Log.d("#paymentOptionsRequest" , paymentOptionsRequest.getPaymentOptionRequestInfo());
```
```
System.out.println("getPaymentOptions>>> error: "+errorDetails.getErrorMessage());
System.out.println("getPaymentOptions>>> error: "+errorDetails.getErrorBody());
```
From my point of view this is a big security issue, and it's a blocker to migrate to this version.

**Comment by matir91** [comment]
I suggest to add a custom logger or a debug flag

**Comment by matir91** [comment]
Hi, in my opinion this is a major issue, the credit card number is logged in the system logger and it's a big risk. It's blocking my release, What do you think? Do you plan to fix it?
Thanks!

**Comment by HaithamSheshtawy** [comment]
HI,
Thank you in advance for your valuable feedback. 

FYI. Now release 2.2.4
The main target of this release is to " Stop Logging SDK info and let SDK follows client app language ".

Let me know if you face any other issues.
Regards,
