### ISSUE TITLE
Changelog File

### ISSUE THREAD

**Issue by matir91** [Tap-Payments/goSellSDK-Android#13]
Can you include the version changes in a changelog file or in the [release section](https://github.com/Tap-Payments/goSellSDK-Android/releases) please?
So, when you release a new version we can know easier what changed.

Thanks!

**Comment by HaithamSheshtawy** [comment]
will be added.

**Comment by matir91** [comment]
ok, it would be nice if in the future you can create releases instead of tags. For example you could do something like [this](https://github.com/xmartlabs/android-snapshot-publisher/releases).
