### ISSUE TITLE
[2.2.1] Activities launch Mode

### ISSUE THREAD

**Issue by matir91** [Tap-Payments/goSellSDK-Android#14]
All activities from the sdk should use `singleTask` or at least `singleTop` to avoid opens the payment view multiple times.

**Comment by HaithamSheshtawy** [comment]
Provide more details about your issues

**Comment by matir91** [comment]
Hi, the thing here is that if you call the pay mehod twice, for example suppose that the user taps twice the pay button quickly, the payment view will be opened twice. That happened mainly because the sdk doesn't define the lunch mode in their activities. I recommend you to read the[ activity's documentation](https://developer.android.com/guide/topics/manifest/activity-element), but in this case I suggest you to use singleTask, because 2 instance of the payment's activities shouldn't be opened twice in the same activity's stack.

**Comment by HaithamSheshtawy** [comment]
- Disabling button after the first click has to be implemented in
client Activity. SDK has callbacks to notify client activity with its
current status.

**Comment by matir91** [comment]
That's ok, but why is the main reason why you don't like to use the right `launchMode`? Do you think that the right launch mode is `standard`?

**Comment by matir91** [comment]
@HaithamSheshtawy related with this, when you are paying, if you click the select currency button multiple times it opens the select currency screen multiple times. It's related with the same issue

**Comment by HaithamSheshtawy** [comment]
- SDK updated to have only one session at a time and it will be available in goSellSDK-Android:2.2.8.
