### ISSUE TITLE
[2.2.3] Sdk Language doesn't work

### ISSUE THREAD

**Issue by matir91** [Tap-Payments/goSellSDK-Android#15]
The sdk is using the device language instead of the sdk language.

If you have the phone in Arabic and you setup the sdk to use English, the payment view is in Arabic instead of English.
```kotlin
ThemeObject.getInstance().setSdkLanguage("en")
GoSellSDK.setLocale("en")
sdkSession.start(activity)
```

The same issue happened if you have the phone in English and you try to use the sdk in Arabic

**Comment by HaithamSheshtawy** [comment]
the sdk language follows the client app language. So the sdk activities layout direction will follow your app layout direction.
