### ISSUE TITLE
KNET payment screen is blank after loading finishes.

### ISSUE THREAD

**Issue by umar2121** [Tap-Payments/goSellSDK-Android#19]
I have integrated GoSellSDK in my application. Everything else is working fine but when I choose KNET as payment method nothing shows after the loading finishes. 

My keys are correct and KNET is activated on them. KNET is working fine for the test key but doesn't work on my live key.

![Screenshot_20190617-115903](https://user-images.githubusercontent.com/12980354/59677749-08ef9200-91e4-11e9-89b4-09260c2b8802.png)

**Comment by HaithamSheshtawy** [comment]
We check with Backend, and we will inform you as soon as possible.
Thank you.

**Comment by HaithamSheshtawy** [comment]
Issue closed .

**Comment by umar2121** [comment]
I'm still getting the same issue on Live Keys. Please reopen the issue and help me find a solution. Thanks.

**Comment by Haitham001** [comment]
Knet is not working in Pakistan. You have to test in other locations or using VPN.
