### ISSUE TITLE
OTP Page refreshed when came back from the SMS application

### ISSUE THREAD

**Issue by chirag-raval** [Tap-Payments/goSellSDK-Android#28]
Hello,

I got a very strange issue in the payment SDK when I go to the SMS application and came back to the OTP page to enter the OPT, the page refreshed every time.

Can anyone face the same issue? I am having this issue in Redmi Note 5 Android device.

**Comment by HaithamSheshtawy** [comment]
can u integrate with com.github.Tap-Payments:goSellSDK-Android:2.4.5.3 and let me kn

**Comment by HaithamSheshtawy** [comment]
We upgraded our internal SDK Gradle:
  - com.squareup.retrofit2:retrofit:2.6.0
  - com.squareup.retrofit2:converter-gson:2.6.0

Can u integrate with "com.github.Tap-Payments:goSellSDK-Android:2.4.5.3" and let me know. 

I can't reproduce it so please, Also, could u please provide me with devices that cause this issue.

**Comment by chirag-raval** [comment]
Hi, Haitham.

We have used AndroidX, can you please provide a link for Android X?

**Comment by HaithamSheshtawy** [comment]
AndroidX
   implementation 'com.github.Tap-Payments:goSellSDK-AndroidX:3.2.5'

**Comment by HaithamSheshtawy** [comment]
implementation 'com.github.Tap-Payments:goSellSDK-AndroidX:3.2.5'

**Comment by HaithamSheshtawy** [comment]
Are you able to integrate with X version 3.2.5
