### ISSUE TITLE
[2.4.6] The library doesn't compile

### ISSUE THREAD

**Issue by matir91** [Tap-Payments/goSellSDK-Android#29]
### Log:
```
> Task :library:generateDebugRFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:generateDebugRFile'.
> Could not resolve all files for configuration ':library:debugRuntimeClasspath'.
   > Could not resolve com.github.Tap-Payments:TapCardValidator-Android:2.1.0.1.
     Required by:
         project :library
      > Could not resolve com.github.Tap-Payments:TapCardValidator-Android:2.1.0.1.
         > Could not get resource 'https://jitpack.io/com/github/Tap-Payments/TapCardValidator-Android/2.1.0.1/TapCardValidator-Android-2.1.0.1.pom'.
            > Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapCardValidator-Android/2.1.0.1/TapCardValidator-Android-2.1.0.1.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Steps to reproduce it: 
- Clone the repo (`git clone git@github.com:Tap-Payments/goSellSDK-Android.git`).
- Checkout in the 2.4.6 tag (`git checkout 2.4.6 `)
- Compile it `./gradlew  assembleDebug`

### Additional comments:
- I tested the goSellSDK-AndroidX version and It has the same issue https://github.com/Tap-Payments/goSellSDK-AndroidX/issues/4.
- Your ci server is facing the same issue:
https://travis-ci.org/Tap-Payments/goSellSDK-Android/builds/606371366

**Comment by HaithamSheshtawy** [comment]
now its public, can u please test

**Comment by matir91** [comment]
It's not working. More dependencies are missing.
```
* What went wrong:
Execution failed for task ':goSellSDKSample:mergeDebugAssets'.
> Could not resolve all files for configuration ':goSellSDKSample:debugRuntimeClasspath'.
   > Could not resolve com.github.Tap-Payments:TapFontsKit-Android:1.0.
     Required by:
         project :goSellSDKSample
      > Could not resolve com.github.Tap-Payments:TapFontsKit-Android:1.0.
         > Could not get resource 'https://jitpack.io/com/github/Tap-Payments/TapFontsKit-Android/1.0/TapFontsKit-Android-1.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapFontsKit-Android/1.0/TapFontsKit-Android-1.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.github.Tap-Payments:TapDimensionsKit-Android:1.0.
     Required by:
         project :goSellSDKSample
      > Could not resolve com.github.Tap-Payments:TapDimensionsKit-Android:1.0.
         > Could not get resource 'https://jitpack.io/com/github/Tap-Payments/TapDimensionsKit-Android/1.0/TapDimensionsKit-Android-1.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapDimensionsKit-Android/1.0/TapDimensionsKit-Android-1.0.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
16 actionable tasks: 16 executed
```

You can try it following the same steps as before.

**Comment by HaithamSheshtawy** [comment]
Now both TapDimensionsKit-Android and TapFontsKit-Android are public can u check now

**Comment by matir91** [comment]
So I tried it but I'm still facing the same issue. Did you try with the steps I posted in the description of this issue?

**Comment by HaithamSheshtawy** [comment]
I reproduced your scenario as mentioned in the description, and everything is working fine.
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/45915302/68329689-ddae0680-00e2-11ea-8b43-f0cb295097b6.png">

But, can you just add implementation 'com.github.Tap-Payments:goSellSDK-Android:2.4.6' as a dependency to your project and sync. don't test it through goSellSDKSample

**Comment by HaithamSheshtawy** [comment]
Also, this is jit pack artifact report:
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/45915302/68330097-b0158d00-00e3-11ea-90ce-02e5f17fd976.png">

**Comment by matir91** [comment]
I'm still having issues, now we have another dependency with issues:

```
 What went wrong:
Execution failed for task ':library:generateReleaseRFile'.
> Could not resolve all files for configuration ':library:releaseRuntimeClasspath'.
   > Could not resolve com.github.Tap-Payments:TapGLKit-Android:1.15.
     Required by:
         project :library
      > Could not resolve com.github.Tap-Payments:TapGLKit-Android:1.15.
         > Could not get resource 'https://jitpack.io/com/github/Tap-Payments/TapGLKit-Android/1.15/TapGLKit-Android-1.15.pom'.
            > Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapGLKit-Android/1.15/TapGLKit-Android-1.15.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
7 actionable tasks: 1 executed, 6 up-to-date

```

I tried it in your project and also in my app. 
If you want to reproduce the issue you can clone your project and execute `./gradlew :library:assembleRelease --refresh-dependencies`. Keep in mind that I added `--refresh-dependencies ` flag in order to reload all dependencies, because that dependency was working fine but it's not working anymore.

**Comment by HaithamSheshtawy** [comment]
It seems you face different issues each time. and I have doubts about JitPack itself.
So, I reproduced your scenario again. I made the lib public.
can you test it now?

**Comment by HaithamSheshtawy** [comment]
TapGLKit-Android:1.15
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/45915302/68364747-e680f580-013f-11ea-87e1-68e9c85092be.png">

**Comment by HaithamSheshtawy** [comment]
Could u please close the issue If you be able to integrate.

**Comment by matir91** [comment]
Yep, it's working now. Thanks!

**Comment by HaithamSheshtawy** [comment]
Great
Most welcome.

**Comment by atanvir** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':goSellSDKSample:mergeDebugAssets'.
> Could not resolve all files for configuration ':goSellSDKSample:debugRuntimeClasspath'.
   > Could not resolve com.github.Tap-Payments:TapColorsKit-Android:1.0.
     Required by:
         project :goSellSDKSample
      > Could not resolve com.github.Tap-Payments:TapColorsKit-Android:1.0.
         > Could not get resource 'https://jitpack.io/com/github/Tap-Payments/TapColorsKit-Android/1.0/TapColorsKit-Android-1.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapColorsKit-Android/1.0/TapColorsKit-Android-1.0.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
