### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Parasghasadiya** [Tap-Payments/goSellSDK-Android#35]
FAILURE: Build failed with an exception.
I just check out the code from https://github.com/Tap-Payments/goSellSDK-AndroidX.git
[
![Screenshot from 2020-08-17 16-56-16](https://user-images.githubusercontent.com/11610438/90391666-21d72a00-e0ab-11ea-8b86-a2a0e1102559.png)
](url)

Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapColorsKit-Android/1.0/TapColorsKit-Android-1.0.pom'
[
![Screenshot from 2020-08-17 17-04-22](https://user-images.githubusercontent.com/11610438/90392036-c6f20280-e0ab-11ea-8b80-9030b0967c12.png)
](url)

**Comment by ayoub96anbara** [comment]
same issue
