### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by enggazzar** [Tap-Payments/goSellSDK-Android#37]
{"errors":[{"code":"2104","description":"Invalid API Key"}]}

**Comment by AhlaamK-tap** [comment]
Hi @enggazzar 
Please send email tap support team **support@tap.company** to register your bundle id with Tap and get the secret key.

**Comment by Abd-Allah-muhammed-muhammed** [comment]
same error{"errors":[{"code":"2104","description":"Invalid API Key"}]}

**Comment by AhlaamK-tap** [comment]
Hi Could you please share the details of error and package id and secret key to this email **a.kazi@tap.company**
