### ISSUE TITLE
401 invalid api key

### ISSUE THREAD

**Issue by akshar247** [Tap-Payments/goSellSDK-Android#38]

**Comment by AhlaamK-tap** [comment]
Hi @akshar247 Please make sure to register your bundle ID with tap and use the generated keys,
Kindly send email tap support team **support@tap.company**

**Comment by HarshitPadalia** [comment]
How can I register my bundle id?

**Comment by AhlaamK-tap** [comment]
Kindly send an email to tap support team at the below id
support@tap.company

Thanks
