### ISSUE TITLE
Create Token PCI Permission issue

### ISSUE THREAD

**Issue by RaziaSandhu** [Tap-Payments/goSellSDK-Android#4]
I am facing issue when creating token in TAP payment gateway as below:

403, errorBody: {"status":"fail","type":"permission_denied","message":"It is likely that you need to grant has_pci_dss permission"}, throwable: null

Please reply

**Comment by AliElDerawi** [comment]
Hi @RaziaSandhu  ,

I have the same error, 
did you find a way to fix it?

Regards,
Ali

**Comment by RaziaSandhu** [comment]
Yes i solved this

**Comment by RaziaSandhu** [comment]
Pass source null and you will get URL of payment and open in web view.This will collect card  detail

**Comment by RaziaSandhu** [comment]
and use 
GoSellAPI.getInstance(AUTH_TOKEN).createCharge(
    new CreateChargeRequest  ................................

**Comment by RaziaSandhu** [comment]
Let me know when you done

**Comment by AliElDerawi** [comment]
Hi @RaziaSandhu 

Nice trick, thank you very much!

I got the URL of payment then I opened it, which directed me to card detail screen.
There's a second issue, I don't know if you had.
I used Secret API key available in the [Testing section](https://www.tap.company/ar/developers/) and the process of the transaction completed successfully, when trying to use my secret from goSell API Credentials (Sandbox or Production) it is always failed (using Test card or real card).

I think I should contact the support team.

**Comment by RaziaSandhu** [comment]
Great @AliElDerawi glad to hear. I want to tell you that this is not trick I have contacted with TAP support team and they explain everything.

**Comment by RaziaSandhu** [comment]
I did not face issue you explained.

**Comment by AliElDerawi** [comment]
Thanks very much for the clarification @RaziaSandhu 

Could I take a little more of your time?
About using webview, after a transaction has been completed, it will redirect to (return_url) page. 
I wonder how you managed to exit and return back to android activity after completing a transaction?

Thank you.

**Comment by RaziaSandhu** [comment]
Yah sure, there is success message in url, You need to get all parameter with return url and identify that success or failure

**Comment by srikanthguttula** [comment]
web page not opening while run this code

**Comment by srikanthguttula** [comment]
About using webview, after a transaction has been completed, it will redirect to (return_url) page.did u solve this issue.iam unable catch the succcess to move back to the activity.

**Comment by srikanthguttula** [comment]
hi @AliElDerawi ,is any backend required to create returnurl (http://return.com/returnurl).what should i replace in this return and posturl, iam getting this error after payment successfull screen.

The webpage at http://return.com/returnurl?chargeid=ch_p1BT2018627Pl011794810&ref=3010172018064254583&result=SUCCESS&payid=TST_10263767220181017&crdtype=MASTERCARD&trackid=Trans%20ref&crd=0008&hash=4cfb9a23210cac4b5f0be8e8d3fdfcd3cb92e1c1a2fa1b2baad849612a314d29 could not be loaded because:

net::ERR_CLEARTEXT_NOT_PERMITTED

**Comment by om4rezz** [comment]
> Pass source null and you will get URL of payment and open in web view.This will collect card detail

where to pass???

**Comment by AliElDerawi** [comment]
Hi @srikanthguttula ,
I've just noticed that you've edited your question.
No, you don't have to create a backend for returnurl.
You should exchange it with your own website url, and any page will pass.

**Comment by AliElDerawi** [comment]
Hi @om4rezz ,
Pass it here. 
GoSellAPI.getInstance(AUTH_TOKEN).createCharge(
    new CreateChargeRequest
      ....
      ....
        .source(new CreateChargeRequest.Source(null))

You will get Url of payment in response > redirect.

**Comment by 00AhmedMokhtar00** [comment]
same issue here when using test key from my account:  

{"status":"fail","type":"permission_denied","message":"It is likely that you need to grant has_pci_dss permission","error":null}

**Comment by muhammadessam** [comment]
I have the same problem now to the end point
https://api.tap.company/v2/tokens
here is the response: 
{
  "status": "fail",
  "type": "permission_denied",
  "message": "It is likely that you need to grant has_pci_dss permission"
}


and here is the request body:
{
    "card": {
        "number": 4012000033330026,
        "exp_month": 5,
        "exp_year": 21,
        "cvc": 100,
        "name": "Test lasd",
        "address": {
            "country": "Kuwait",
            "line1": "Salmiya, 21",
            "city": "Kuwait city",
            "street": "Salim",
            "avenue": "Gulf"
        }
    },
    "client_ip": "192.168.1.20"
}

i'm testing the API using post man and it's not working

**Comment by HaithamSheshtawy** [comment]
You are not a PCI, so you need a public key to encrypt the card data. Try
to use the SDK
[image: Logo] <http://tap.company/kw/en>
Haitham Elsheshtawy | Tech Lead
a: tap payments  | 8 Mall Floor no. 6, Salem Al Mubarak St, Salmiya, Kuwait
e: ***@***.*** | w: tap.company/kw/en <http://tap.company/kw/en>

m: + 965 65562630
[image: facebook icon] <https://www.facebook.com/haitham.m.sheshtawy> [image:
linkedin icon] <https://www.linkedin.com/in/haitham-el-sheshtawy-55a33420/>
[image:
instagram icon] <https://www.instagram.com/haitham_sheshtawy/>

**Comment by USAMA-R-Y** [comment]
> Pass source null and you will get URL of payment and open in web view.This will collect card detail

are you available? I am facing same issue. need help very urgently.

**Comment by zain148** [comment]
> I have the same problem now to the end point
> https://api.tap.company/v2/tokens
> here is the response:
> {
> "status": "fail",
> "type": "permission_denied",
> "message": "It is likely that you need to grant has_pci_dss permission"
> }
> 
> and here is the request body:
> {
> "card": {
> "number": 4012000033330026,
> "exp_month": 5,
> "exp_year": 21,
> "cvc": 100,
> "name": "Test lasd",
> "address": {
> "country": "Kuwait",
> "line1": "Salmiya, 21",
> "city": "Kuwait city",
> "street": "Salim",
> "avenue": "Gulf"
> }
> },
> "client_ip": "192.168.1.20"
> }
> 
> i'm testing the API using post man and it's not working
> and i'm using my own secrete key

Same error any one here to support?

**Comment by RanaUsama20** [comment]
> > I have the same problem now to the end point
> > https://api.tap.company/v2/tokens
> > here is the response:
> > {
> > "status": "fail",
> > "type": "permission_denied",
> > "message": "It is likely that you need to grant has_pci_dss permission"
> > }
> > and here is the request body:
> > {
> > "card": {
> > "number": 4012000033330026,
> > "exp_month": 5,
> > "exp_year": 21,
> > "cvc": 100,
> > "name": "Test lasd",
> > "address": {
> > "country": "Kuwait",
> > "line1": "Salmiya, 21",
> > "city": "Kuwait city",
> > "street": "Salim",
> > "avenue": "Gulf"
> > }
> > },
> > "client_ip": "192.168.1.20"
> > }
> > i'm testing the API using post man and it's not working
> > and i'm using my own secrete key
> 
> Same error any one here to support?

i am having the same issue , did you solve it?
