### ISSUE TITLE
Payment view show automatic when page is load

### ISSUE THREAD

**Issue by navneetboghani** [Tap-Payments/goSellSDK-Android#41]
Payment view is showing automatic when page is load, i want to show payment view when user click on button

**Comment by AhlaamK-tap** [comment]
You should  do this  /**
             * Use this method where ever you want to show TAP SDK Main Screen.
             * This method must be called after you configured SDK as above
             * This method will be used in case of you are not using TAP PayButton in your activity.
<img width="927" alt="Screen Shot 2023-01-11 at 5 10 28 PM" src="https://user-images.githubusercontent.com/57221514/211827447-f92af6fb-2df0-44b7-8f14-7314debea46d.png">

             */
            sdkSession.start(this)
