### ISSUE TITLE
errorBody{"errors":[{"code":"2104","description":"Invalid API Key"}]}

### ISSUE THREAD

**Issue by Yousaf128** [Tap-Payments/goSellSDK-Android#45]
i am getting this error while adding test/live key in it. 

errorBody{"errors":[{"code":"2104","description":"Invalid API Key"}]}

**Comment by HaithamSheshtawy** [comment]
Please send an email ***@***.***

**Comment by moazelsawaf** [comment]
Same issue

**Comment by AhlaamK-tap** [comment]
@moazelsawaf 
Kindly send an email to tap support team at the below id
support@tap.company

Thanks
