### ISSUE TITLE
App getting crash while proceed Payment

### ISSUE THREAD

**Issue by Yousaf128** [Tap-Payments/goSellSDK-Android#46]
I am getting below Error in  2.15.3 and 2.15.4
Binary XML file line #36 in :layout/gosellapi_viewholder_recent_payments: Binary XML file line #36 in :layout/gosellapi_viewholder_recent_payments: Error inflating class <unknown>

 Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

**Comment by AhlaamK-tap** [comment]
If Material design is used i.e. It' androidX please refer to use the  
[(https://github.com/Tap-Payments/goSellSDK-AndroidX)] 
Thanks
