### ISSUE TITLE
Unable to resolve CreateChargeRequest.Customer, CreateChargeRequest.Receipt and CreateChargeRequest.Source classes

### ISSUE THREAD

**Issue by umar2121** [Tap-Payments/goSellSDK-Android#7]
I'm trying to add this SDK in a project and I'm unable to Resolve the following classes when creating a charge:
- CreateChargeRequest.Customer
- CreateChargeRequest.Receipt
- CreateChargeRequest.Source

I tried adding a Customer object retrieved from GoSellAPI.getInstance(AUTH_TOKEN).createCustomer but it doesn't work either.

Any help would be appreciated. Thanks.
![image](https://user-images.githubusercontent.com/12980354/54599787-2f732500-4a5d-11e9-86c2-b20812ad6f26.png)

**Comment by HaithamSheshtawy** [comment]
review our documentation "ReadMe" to figure out how u can start SDK Screen. You cannot create ChargeRequest directly
