### ISSUE TITLE
Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by ravivghl** [Tap-Payments/goSellSDK-Android#8]
I am getting issue with 'com.github.Tap-Payments:goSellSDK-Android:2.1.10' library import.

**Comment by HaithamSheshtawy** [comment]
upgrade to 'com.github.Tap-Payments:goSellSDK-Android:2.1.12'. Also be sure that you are included  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
in your griddle

**Comment by ravivghl** [comment]
yes. Working right now. Thank you. @HaithamSheshtawy

**Comment by HaithamSheshtawy** [comment]
Great
