### ISSUE TITLE
Invalid API key error while using the correct test keys.

### ISSUE THREAD

**Issue by umar2121** [Tap-Payments/goSellSDK-Android#9]
I'm facing an issue. I have integrated the latest version of SDK in an application. But when I try to run it by calling configureSDKSession method. I always end up in "sdkError" callback with an error message of:
 {"errors":[{"code":"2104","description":"Invalid API Key"}]}

I've tried using the test keys from my TAP Merchant panel. 
I've also tried the test keys mentioned on the TAP Documentation.

**Comment by matir91** [comment]
I had a similar issue, the app's package was not registered in their system

**Comment by Haitham001** [comment]
kindly check with the backend system that your app's package is registered.
*Sincerely,*
*Haitham Elsheshtawy*
*http://about.me/Haitham.Sheshtawy <http://about.me/Haitham.Sheshtawy>*

**Comment by NaisargiPatel** [comment]
Hi @Haitham001 @matir91 
How to register app's package. They are not mentioning any options in the console.

**Comment by HaithamSheshtawy** [comment]
HI @NaisargiPatel 
You have to contact Tap Support Team at:
  support@tap.company     
  t.kalai@tap.company.

**Comment by HaithamSheshtawy** [comment]
HI @NaisargiPatel <https://github.com/NaisargiPatel>
You have to contact Tap Support Team at:
support@tap.company
t.kalai@tap.company.

**Comment by NaisargiPatel** [comment]
@HaithamSheshtawy Thank you for your support

**Comment by HaithamSheshtawy** [comment]
HI @youssef-be You have to contact Tap Support Team at:
support@tap.company
t.kalai@tap.company.

**Comment by HaithamSheshtawy** [comment]
Please contact
mailto:support@tap.company

**Comment by MarvelSystems0** [comment]
I had a similar issue, i wish found correct solution here.. please!****

**Comment by HarshitPadalia** [comment]
I am having same issue
